# Raw data

p1<-ggplot(data=rawcounts,aes(x=BA_A_150 + 1,y=BA_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_150+1) ~ log10(BA_B_150 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_150+1,y=BA_B_150+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 150.")
p2<-ggplot(data=rawcounts,aes(x=BA_A_15 + 1,y=BA_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_15+1) ~ log10(BA_B_15 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_15+1,y=BA_B_15+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 15.")
p3<-ggplot(data=rawcounts,aes(x=BA_A_270 + 1,y=BA_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_270+1) ~ log10(BA_B_270 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_270+1,y=BA_B_270+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 270.")
p4<-ggplot(data=rawcounts,aes(x=BA_A_75 + 1,y=BA_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_75+1) ~ log10(BA_B_75 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_75+1,y=BA_B_75+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 75.")
p5<-ggplot(data=rawcounts,aes(x=BuOH_A_150 + 1,y=BuOH_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_150+1) ~ log10(BuOH_B_150 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_150+1,y=BuOH_B_150+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 150.")
p6<-ggplot(data=rawcounts,aes(x=BuOH_A_15 + 1,y=BuOH_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_15+1) ~ log10(BuOH_B_15 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_15+1,y=BuOH_B_15+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 15.")
p7<-ggplot(data=rawcounts,aes(x=BuOH_A_270 + 1,y=BuOH_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_270+1) ~ log10(BuOH_B_270 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_270+1,y=BuOH_B_270+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 270.")
p8<-ggplot(data=rawcounts,aes(x=BuOH_A_75 + 1,y=BuOH_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_75+1) ~ log10(BuOH_B_75 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_75+1,y=BuOH_B_75+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 75.")
p9<-ggplot(data=rawcounts,aes(x=NS_A_150 + 1,y=NS_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_150+1) ~ log10(NS_B_150 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_150+1,y=NS_B_150+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 150.")
p10<-ggplot(data=rawcounts,aes(x=NS_A_15 + 1,y=NS_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_15+1) ~ log10(NS_B_15 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_15+1,y=NS_B_15+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 15.")
p11<-ggplot(data=rawcounts,aes(x=NS_A_270 + 1,y=NS_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_270+1) ~ log10(NS_B_270 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_270+1,y=NS_B_270+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 270.")
p12<-ggplot(data=rawcounts,aes(x=NS_A_75 + 1,y=NS_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_75+1) ~ log10(NS_B_75 + 1), rawcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_75+1,y=NS_B_75+1,colour="best fit"),data=rawcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 75.")
p<-arrangeGrob(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,ncol=3)
ggsave("summary/images/rawcount_cor.png",p)


# Normalized counts

p1<-ggplot(data=normcounts,aes(x=BA_A_150 + 1,y=BA_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_150+1) ~ log10(BA_B_150 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_150+1,y=BA_B_150+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 150.")
p2<-ggplot(data=normcounts,aes(x=BA_A_15 + 1,y=BA_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_15+1) ~ log10(BA_B_15 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_15+1,y=BA_B_15+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 15.")
p3<-ggplot(data=normcounts,aes(x=BA_A_270 + 1,y=BA_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_270+1) ~ log10(BA_B_270 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_270+1,y=BA_B_270+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 270.")
p4<-ggplot(data=normcounts,aes(x=BA_A_75 + 1,y=BA_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BA_A_75+1) ~ log10(BA_B_75 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BA_A_75+1,y=BA_B_75+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 75.")
p5<-ggplot(data=normcounts,aes(x=BuOH_A_150 + 1,y=BuOH_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_150+1) ~ log10(BuOH_B_150 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_150+1,y=BuOH_B_150+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 150.")
p6<-ggplot(data=normcounts,aes(x=BuOH_A_15 + 1,y=BuOH_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_15+1) ~ log10(BuOH_B_15 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_15+1,y=BuOH_B_15+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 15.")
p7<-ggplot(data=normcounts,aes(x=BuOH_A_270 + 1,y=BuOH_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_270+1) ~ log10(BuOH_B_270 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_270+1,y=BuOH_B_270+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 270.")
p8<-ggplot(data=normcounts,aes(x=BuOH_A_75 + 1,y=BuOH_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(BuOH_A_75+1) ~ log10(BuOH_B_75 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=BuOH_A_75+1,y=BuOH_B_75+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 75.")
p9<-ggplot(data=normcounts,aes(x=NS_A_150 + 1,y=NS_B_150 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_150+1) ~ log10(NS_B_150 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_150+1,y=NS_B_150+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 150.")
p10<-ggplot(data=normcounts,aes(x=NS_A_15 + 1,y=NS_B_15 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_15+1) ~ log10(NS_B_15 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_15+1,y=NS_B_15+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 15.")
p11<-ggplot(data=normcounts,aes(x=NS_A_270 + 1,y=NS_B_270 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_270+1) ~ log10(NS_B_270 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_270+1,y=NS_B_270+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 270.")
p12<-ggplot(data=normcounts,aes(x=NS_A_75 + 1,y=NS_B_75 + 1)) + geom_point(alpha=0.5,size=2)+scale_y_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+scale_x_log10(breaks=10**(0:4),labels=trans_format("log10",math_format(10^.x)))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=20,y=2000,label=lm_eqn(lm(log10(NS_A_75+1) ~ log10(NS_B_75 + 1), normcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=NS_A_75+1,y=NS_B_75+1,colour="best fit"),data=normcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 75.")
p<-arrangeGrob(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,ncol=3)
ggsave("summary/images/normcount_cor.png",p)


# Regularized Counts
p1<-ggplot(data=regcounts,aes(x=(BA_A_150 + 1)/log2(10),y=(BA_B_150 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BA_A_150+1 ~ BA_B_150 + 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BA_A_150+1)/log2(10),y=(BA_B_150+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 150.")
p2<-ggplot(data=regcounts,aes(x=(BA_A_15 + 1)/log2(10),y=(BA_B_15 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BA_A_15+1~ BA_B_15 + 1,regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BA_A_15+1)/log2(10),y=(BA_B_15+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 15.")
p3<-ggplot(data=regcounts,aes(x=(BA_A_270 + 1)/log2(10),y=(BA_B_270 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BA_A_270+1~ BA_B_270 + 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BA_A_270+1)/log2(10),y=(BA_B_270+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 270.")
p4<-ggplot(data=regcounts,aes(x=(BA_A_75 + 1)/log2(10),y=(BA_B_75 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BA_A_75+1~ BA_B_75 + 1,regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BA_A_75+1)/log2(10),y=(BA_B_75+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BA 75.")
p5<-ggplot(data=regcounts,aes(x=(BuOH_A_150 + 1)/log2(10),y=(BuOH_B_150 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BuOH_A_150+1~BuOH_B_150+ 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BuOH_A_150+1)/log2(10),y=(BuOH_B_150+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 150.")
p6<-ggplot(data=regcounts,aes(x=(BuOH_A_15 + 1)/log2(10),y=(BuOH_B_15 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BuOH_A_15+1~BuOH_B_15 +1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BuOH_A_15+1)/log2(10),y=(BuOH_B_15+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 15.")
p7<-ggplot(data=regcounts,aes(x=(BuOH_A_270 + 1)/log2(10),y=(BuOH_B_270 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BuOH_A_270+1~BuOH_B_270+ 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BuOH_A_270 +1)/log2(10),y=(BuOH_B_270+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 270.")
p8<-ggplot(data=regcounts,aes(x=(BuOH_A_75 + 1)/log2(10),y=(BuOH_B_75 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(BuOH_A_75+1~BuOH_B_75 +1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(BuOH_A_75+1)/log2(10),y=(BuOH_B_75+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: BuOH 75.")
p9<-ggplot(data=regcounts,aes(x=(NS_A_150 + 1)/log2(10),y=(NS_B_150 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(NS_A_150+1~ NS_B_150 + 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(NS_A_150+1)/log2(10),y=(NS_B_150+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 150.")
p10<-ggplot(data=regcounts,aes(x=(NS_A_15 + 1)/log2(10),y=(NS_B_15 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(NS_A_15+1~ NS_B_15 + 1,regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(NS_A_15+1)/log2(10),y=(NS_B_15+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 15.")
p11<-ggplot(data=regcounts,aes(x=(NS_A_270 + 1)/log2(10),y=(NS_B_270 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(NS_A_270+1~ NS_B_270 + 1, regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(NS_A_270+1)/log2(10),y=(NS_B_270+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 270.")
p12<-ggplot(data=regcounts,aes(x=(NS_A_75 + 1)/log2(10),y=(NS_B_75 + 1)/log2(10))) + geom_point(alpha=0.5,size=2)+scale_y_continuous(labels=math_format(10^.x))+scale_x_continuous(labels=math_format(10^.x))+annotation_logticks(base=10,sides='bl')+geom_abline(intercept=0,slope=1,size=1,col="blue")+annotate("text",x=1,y=3,label=lm_eqn(lm(NS_A_75+1~ NS_B_75 + 1,regcounts)),colour="black",size=5,parse=TRUE)+stat_smooth(aes(x=(NS_A_75+1)/log2(10),y=(NS_B_75+1)/log2(10),colour="best fit"),data=regcounts,method="lm",size=1,na.rm=TRUE,fullrange=TRUE)+scale_colour_discrete("")+ggtitle("Count Correlation: NS 75.")

p<-arrangeGrob(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,ncol=3)
ggsave("summary/images/regcount_cor.png",p)
